// Golf Utah — Course Database
// Each course has: id, name, region, system (foreup|chronogolf|custom), and system-specific config

const COURSES = [

  // ─── CHRONOGOLF COURSES ───────────────────────────────────────────────────
  // Chronogolf slug is found at: chronogolf.com/club/{slug}
  // The booking widget also lives at that URL — we scrape the tee times API it calls

  {
    id: "thanksgiving-point",
    name: "Thanksgiving Point Golf Course",
    city: "Lehi",
    region: "utah-valley",
    system: "chronogolf",
    slug: "thanksgiving-point",                 // chronogolf.com/club/{slug}
    courseId: null,                              // filled in after first scrape
    bookingUrl: "https://www.chronogolf.com/club/thanksgiving-point",
    lat: 40.4070, lng: -111.8955,
  },
  {
    id: "sleepy-ridge",
    name: "The Links at Sleepy Ridge",
    city: "Orem",
    region: "utah-valley",
    system: "chronogolf",
    slug: "sleepy-ridge",
    courseId: null,
    bookingUrl: "https://www.chronogolf.com/club/sleepy-ridge",
    lat: 40.2969, lng: -111.6944,
  },
  {
    id: "soldier-hollow",
    name: "Soldier Hollow Golf Course",
    city: "Midway",
    region: "heber",
    system: "chronogolf",
    slug: "soldier-hollow-golf-course",
    courseId: null,
    bookingUrl: "https://www.chronogolf.com/club/soldier-hollow-golf-course",
    lat: 40.5072, lng: -111.4765,
  },
  {
    id: "wasatch-mountain",
    name: "Wasatch Mountain Golf Course",
    city: "Midway",
    region: "heber",
    system: "chronogolf",
    slug: "wasatch-mountain-state-park",
    courseId: null,
    bookingUrl: "https://www.chronogolf.com/club/wasatch-mountain-state-park",
    lat: 40.5145, lng: -111.5119,
  },
  {
    id: "bonneville",
    name: "Bonneville Golf Course",
    city: "Salt Lake City",
    region: "salt-lake",
    system: "chronogolf",
    slug: "bonneville-golf-course",
    courseId: null,
    bookingUrl: "https://www.chronogolf.com/club/bonneville-golf-course",
    lat: 40.7484, lng: -111.8105,
  },
  {
    id: "rose-park",
    name: "Rose Park Golf Course",
    city: "Salt Lake City",
    region: "salt-lake",
    system: "chronogolf",
    slug: "rose-park-golf-course",
    courseId: null,
    bookingUrl: "https://www.chronogolf.com/club/rose-park-golf-course",
    lat: 40.7923, lng: -111.9283,
  },
  {
    id: "mountain-dell",
    name: "Mountain Dell Golf Course",
    city: "Salt Lake City",
    region: "salt-lake",
    system: "chronogolf",
    slug: "mountain-dell",
    courseId: null,
    bookingUrl: "https://www.chronogolf.com/club/mountain-dell",
    lat: 40.7285, lng: -111.7420,
  },
  {
    id: "glendale",
    name: "Glendale Golf Course",
    city: "Salt Lake City",
    region: "salt-lake",
    system: "chronogolf",
    slug: "glendale-golf-course",
    courseId: null,
    bookingUrl: "https://www.chronogolf.com/club/glendale-golf-course",
    lat: 40.7207, lng: -111.9435,
  },
  {
    id: "forest-dale",
    name: "Forest Dale Golf Course",
    city: "Salt Lake City",
    region: "salt-lake",
    system: "chronogolf",
    slug: "forest-dale-golf-course",
    courseId: null,
    bookingUrl: "https://www.chronogolf.com/club/forest-dale-golf-course",
    lat: 40.7011, lng: -111.8654,
  },
  {
    id: "old-mill",
    name: "Old Mill Golf Course",
    city: "Salt Lake City",
    region: "salt-lake",
    system: "chronogolf",
    slug: "old-mill-golf-course",
    courseId: null,
    bookingUrl: "https://www.chronogolf.com/club/old-mill-golf-course",
    lat: 40.6618, lng: -111.8799,
  },
  {
    id: "meadow-brook",
    name: "Meadow Brook Golf Course",
    city: "Murray",
    region: "salt-lake",
    system: "chronogolf",
    slug: "meadow-brook-golf-course",
    courseId: null,
    bookingUrl: "https://www.chronogolf.com/club/meadow-brook-golf-course",
    lat: 40.6487, lng: -111.8869,
  },
  {
    id: "riverbend",
    name: "Riverbend Golf Course",
    city: "Riverton",
    region: "salt-lake",
    system: "chronogolf",
    slug: "riverbend-golf-course",
    courseId: null,
    bookingUrl: "https://www.chronogolf.com/club/riverbend-golf-course",
    lat: 40.5185, lng: -111.9774,
  },
  {
    id: "sand-hollow-resort",
    name: "Sand Hollow Resort",
    city: "Washington",
    region: "st-george",
    system: "chronogolf",
    slug: "sand-hollow-resort",
    courseId: null,
    bookingUrl: "https://www.chronogolf.com/club/sand-hollow-resort",
    lat: 37.1274, lng: -113.4735,
  },

  // ─── FOREUP COURSES ────────────────────────────────────────────────────────
  // ForeUP booking URL: foreupsoftware.com/index.php/booking/{courseId}/{scheduleId}/
  // The internal API: foreupsoftware.com/index.php/api/booking/times
  // courseId and scheduleId are found in the booking page URL

  {
    id: "valley-view",
    name: "Valley View Golf Course",
    city: "Ogden",
    region: "ogden",
    system: "foreup",
    foreupCourseId: "19757",                    // from booking page URL
    foreupScheduleId: "2078",                   // from booking page URL
    bookingUrl: "https://foreupsoftware.com/index.php/booking/19757/2078/",
    lat: 41.2565, lng: -111.9738,
  },
  {
    id: "ben-lomond",
    name: "Ben Lomond Golf Course",
    city: "Ogden",
    region: "ogden",
    system: "foreup",
    foreupCourseId: "19340",
    foreupScheduleId: "1905",
    bookingUrl: "https://foreupsoftware.com/index.php/booking/19340/1905/",
    lat: 41.2290, lng: -111.9891,
  },
  {
    id: "eaglewood",
    name: "Eaglewood Golf Course",
    city: "North Salt Lake",
    region: "davis",
    system: "foreup",
    foreupCourseId: "19762",
    foreupScheduleId: "2083",
    bookingUrl: "https://foreupsoftware.com/index.php/booking/19762/2083/",
    lat: 40.8490, lng: -111.9072,
  },
  {
    id: "bountiful-ridge",
    name: "Bountiful Ridge Golf Course",
    city: "Bountiful",
    region: "davis",
    system: "foreup",
    foreupCourseId: "19399",
    foreupScheduleId: "1974",
    bookingUrl: "https://foreupsoftware.com/index.php/booking/19399/1974/",
    lat: 40.8794, lng: -111.8512,
  },

  // ─── CUSTOM / DIRECT LINK COURSES ─────────────────────────────────────────
  // These will show up in the app with a "Book Direct" button linking to their site

  {
    id: "wingpointe",
    name: "Wingpointe Golf Course",
    city: "Salt Lake City",
    region: "salt-lake",
    system: "custom",
    bookingUrl: "https://wingpointegolf.com/tee-times/",
    lat: 40.7887, lng: -112.0121,
  },
  {
    id: "black-desert",
    name: "Black Desert Resort",
    city: "Ivins",
    region: "st-george",
    system: "custom",
    bookingUrl: "https://blackdesertutah.com/golf/tee-times/",
    lat: 37.1688, lng: -113.6845,
  },
  {
    id: "entrada",
    name: "Entrada at Snow Canyon Country Club",
    city: "St. George",
    region: "st-george",
    system: "custom",
    bookingUrl: "https://www.entradaclub.com/golf/tee-times",
    lat: 37.1535, lng: -113.6226,
  },
  {
    id: "sunbrook",
    name: "Sunbrook Golf Course",
    city: "St. George",
    region: "st-george",
    system: "custom",
    bookingUrl: "https://sunbrookgolf.com/",
    lat: 37.0878, lng: -113.6237,
  },
  {
    id: "coral-canyon",
    name: "Coral Canyon Golf Course",
    city: "Washington",
    region: "st-george",
    system: "custom",
    bookingUrl: "https://www.coralcanyongolf.com/tee-times/",
    lat: 37.1021, lng: -113.5041,
  },
  {
    id: "spanish-oaks",
    name: "Spanish Oaks Golf Club",
    city: "Spanish Fork",
    region: "utah-valley",
    system: "custom",
    bookingUrl: "https://www.spanishoaksgolf.com/tee-times",
    lat: 40.0882, lng: -111.6165,
  },
  {
    id: "hobble-creek",
    name: "Hobble Creek Golf Course",
    city: "Springville",
    region: "utah-valley",
    system: "custom",
    bookingUrl: "https://www.hobblecreekgolf.com/",
    lat: 40.1465, lng: -111.5698,
  },
  {
    id: "talons-cove",
    name: "TalonsCove Golf Course",
    city: "Saratoga Springs",
    region: "utah-valley",
    system: "custom",
    bookingUrl: "https://www.talonscovegolf.com/tee-times/",
    lat: 40.3447, lng: -111.9124,
  },
];

// Group courses by region for UI
const REGIONS = {
  "salt-lake":   "Salt Lake City",
  "utah-valley": "Utah Valley",
  "ogden":       "Ogden / Weber",
  "davis":       "Davis County",
  "heber":       "Heber / Midway",
  "park-city":   "Park City",
  "st-george":   "St. George",
  "cache":       "Cache Valley",
};

module.exports = { COURSES, REGIONS };
